language: java
sudo: false
script: mvn clean verify
jdk:
  - oraclejdk8
branches:
  only:
    - master
notifications:
  email:
    - shaun.thium@gmail.com
    - jeremyjds@me.com
    - peter.trantiendat@gmail.com
