language: java
sudo: false
script: mvn clean verify coveralls:report
jdk:
  - oraclejdk8
branches:
  only:
    - master
addons:
  apt:
    packages:
      - oracle-java8-installer
notifications:
  email:
    - shaun.thium@gmail.com
    - jeremyjds@me.com
    - peter.trantiendat@gmail.com