language: java
sudo: false
jdk:
  - oraclejdk8
branches:
  only:
    - master
addons:
  apt:
    packages:
      - oracle-java8-installer
notifications:
  email:
    - shaun.thium@gmail.com
    - jeremyjds@me.com
    - peter.trantiendat@gmail.com
after_success:
  - mvn clean test jacoco:report coveralls:report