language: java
sudo: false
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
script: mvn clean verify coveralls:report
jdk:
  - oraclejdk8
branches:
  only:
    - master
addons:
  apt:
    packages:
      - oracle-java8-installer
notifications:
  email:
    - shaun.thium@gmail.com
    - jeremyjds@me.com
    - peter.trantiendat@gmail.com